; generated by ARM C/C++ Compiler, 5.03 [Build 76]
; commandline ArmCC [--c99 --split_sections --debug -c -S -o.\rvmdk\webservices.s --depend=.\rvmdk\webservices.d --cpu=Cortex-M4.fp --apcs=interwork -I.. -I..\ -I..\..\..\.. -I..\cc3100 -I..\cc3100\platform\ek-tm4c123gxl -I..\cc3100\simplelink\include -I..\cc3100\simplelink\source -I..\driverlib -IC:\Keil\ARM\RV31\INC -IC:\Keil\ARM\PACK\ARM\CMSIS\3.20.4\CMSIS\Include -IC:\Keil\ARM\Inc\Luminary -D__MICROLIB -Drvmdk -DPART_TM4C123GH6PM -D_POSIX_SOURCE -DUART_BUFFERED -DTARGET_IS_TM4C123_RB1 --omf_browse=.\rvmdk\webservices.crf WebServices.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.getTime||, CODE, READONLY, ALIGN=2

getTime PROC
        PUSH     {r4-r8,lr}
        MOV      r4,r1
        MOV      r5,r0
        SUB      sp,sp,#0x28
        MOVS     r2,#0x12
        ADR      r1,|L0.456|
        ADD      r0,r0,#0x600
        BL       __aeabi_memcpy4
        MOV      r0,r5
        BL       GetHostIP
        CMP      r0,#0
        BNE      |L0.280|
        MOV      r0,r5
        BL       CreateConnection
        ADD      r6,r5,#0x62c
        MOV      r7,#0xffffffff
        STR      r0,[r5,#0x62c]
        CMP      r0,#0
        BGE      |L0.62|
|L0.54|
        MOV      r0,r7
|L0.56|
        ADD      sp,sp,#0x28
        POP      {r4-r8,pc}
|L0.62|
        ADD      r0,r5,#0x400
        LDR      r1,|L0.476|
        MOV      r8,r0
        BL       strcpy
        MOV      r0,r8
        BL       strlen
        MOV      r2,r0
        MOVS     r3,#0
        MOV      r1,r8
        LDR      r0,[r5,#0x62c]
        BL       sl_Send
        MOVS     r3,#0
        MOV      r2,#0x400
        MOV      r1,r5
        LDR      r0,[r6,#0]
        BL       sl_Recv
        MOV      r0,r5
        BL       strlen
        MOVS     r6,#0
        STRB     r6,[r5,r0]
        ADR      r1,|L0.480|
        MOV      r0,r5
        BL       strstr
        MOVS     r1,r0
        MOV      r0,r6
        ADD      r3,sp,#0x24
        BEQ      |L0.156|
        ADDS     r1,r1,#0xa
        B        |L0.148|
|L0.138|
        STRB     r2,[r3,r0]
        ADDS     r1,r1,#1
        ADDS     r0,r0,#1
        CMP      r0,#0x32
        BCS      |L0.156|
|L0.148|
        LDRB     r2,[r1,#0]
        CBZ      r2,|L0.156|
        CMP      r2,#0x22
        BNE      |L0.138|
|L0.156|
        STRB     r6,[r3,r0]
        ADR      r1,|L0.492|
        MOV      r0,r3
        BL       strcmp
        CBZ      r0,|L0.188|
        ADR      r1,|L0.500|
        MOV      r0,r5
        BL       strstr
        MOVS     r1,r0
        MOV      r0,#0
        BEQ      |L0.258|
        ADDS     r1,r1,#0xf
        B        |L0.250|
|L0.188|
        ADR      r1,|L0.516|
        MOV      r0,r5
        BL       strstr
        MOVS     r1,r0
        MOV      r0,#0
        MOV      r3,sp
        BEQ      |L0.228|
        ADDS     r1,r1,#0xb
        B        |L0.220|
|L0.210|
        STRB     r2,[r3,r0]
        ADDS     r1,r1,#1
        ADDS     r0,r0,#1
        CMP      r0,#0x32
        BCS      |L0.228|
|L0.220|
        LDRB     r2,[r1,#0]
        CBZ      r2,|L0.228|
        CMP      r2,#0x22
        BNE      |L0.210|
|L0.228|
        STRB     r6,[r3,r0]
        MOV      r1,r3
        ADR      r0,|L0.528|
        BL       UARTprintf
        B        |L0.54|
|L0.240|
        STRB     r2,[r4,r0]
        ADDS     r1,r1,#1
        ADDS     r0,r0,#1
        CMP      r0,#0x32
        BCS      |L0.258|
|L0.250|
        LDRB     r2,[r1,#0]
        CBZ      r2,|L0.258|
        CMP      r2,#0x22
        BNE      |L0.240|
|L0.258|
        STRB     r6,[r4,r0]
        ADR      r1,|L0.536|
        MOV      r0,r5
        BL       strstr
        MOVS     r1,r0
        MOV      r0,#0
        BEQ      |L0.302|
        ADDS     r1,r1,#0xc
        B        |L0.294|
|L0.280|
        B        |L0.452|
|L0.282|
        ADDS     r3,r4,r0
        ADDS     r1,r1,#1
        ADDS     r0,r0,#1
        STRB     r2,[r3,#3]
        CMP      r0,#0x32
        BCS      |L0.302|
|L0.294|
        LDRB     r2,[r1,#0]
        CBZ      r2,|L0.302|
        CMP      r2,#0x22
        BNE      |L0.282|
|L0.302|
        ADD      r0,r0,r4
        ADR      r1,|L0.548|
        STRB     r6,[r0,#3]
        MOV      r0,r5
        BL       strstr
        MOVS     r1,r0
        MOV      r0,#0
        BEQ      |L0.346|
        ADDS     r1,r1,#0x10
        B        |L0.338|
|L0.326|
        ADDS     r3,r4,r0
        ADDS     r1,r1,#1
        ADDS     r0,r0,#1
        STRB     r2,[r3,#0x17]
        CMP      r0,#0x32
        BCS      |L0.346|
|L0.338|
        LDRB     r2,[r1,#0]
        CBZ      r2,|L0.346|
        CMP      r2,#0x22
        BNE      |L0.326|
|L0.346|
        ADD      r0,r0,r4
        ADR      r1,|L0.564|
        STRB     r6,[r0,#0x17]
        MOV      r0,r5
        BL       strstr
        MOVS     r1,r0
        MOV      r0,#0
        BEQ      |L0.390|
        ADDS     r1,r1,#0xd
        B        |L0.382|
|L0.370|
        ADDS     r3,r4,r0
        ADDS     r1,r1,#1
        ADDS     r0,r0,#1
        STRB     r2,[r3,#0x1d]
        CMP      r0,#0x32
        BCS      |L0.390|
|L0.382|
        LDRB     r2,[r1,#0]
        CBZ      r2,|L0.390|
        CMP      r2,#0x22
        BNE      |L0.370|
|L0.390|
        ADD      r0,r0,r4
        ADR      r1,|L0.576|
        STRB     r6,[r0,#0x1d]
        MOV      r0,r5
        BL       strstr
        MOVS     r1,r0
        MOV      r0,#0
        ADD      r3,sp,#0x14
        BEQ      |L0.434|
        ADDS     r1,r1,#0xc
        B        |L0.426|
|L0.416|
        STRB     r2,[r3,r0]
        ADDS     r1,r1,#1
        ADDS     r0,r0,#1
        CMP      r0,#0x32
        BCS      |L0.434|
|L0.426|
        LDRB     r2,[r1,#0]
        CBZ      r2,|L0.434|
        CMP      r2,#0x7d
        BNE      |L0.416|
|L0.434|
        STRB     r6,[r3,r0]
        MOV      r0,r3
        BL       atoi
        STR      r0,[r4,#0x24]
        LDR      r0,[r5,#0x62c]
        BL       sl_Close
|L0.452|
        MOVS     r0,#0
        B        |L0.56|
        ENDP

|L0.456|
        DCB      "api.timezonedb.com",0
        DCB      0
|L0.476|
        DCD      ||.constdata||+0xa0
|L0.480|
        DCB      """status""",0
        DCB      0
        DCB      0
        DCB      0
|L0.492|
        DCB      "FAIL",0
        DCB      0
        DCB      0
        DCB      0
|L0.500|
        DCB      """countryCode""",0
        DCB      0
        DCB      0
|L0.516|
        DCB      """message""",0
        DCB      0
        DCB      0
|L0.528|
        DCB      "\n%s\n",0
        DCB      0
        DCB      0
        DCB      0
|L0.536|
        DCB      """zoneName""",0
        DCB      0
|L0.548|
        DCB      """abbreviation""",0
        DCB      0
|L0.564|
        DCB      """gmtOffset""",0
|L0.576|
        DCB      """timestamp""",0

        AREA ||i.getWeather||, CODE, READONLY, ALIGN=2

getWeather PROC
        PUSH     {r4-r7,lr}
        MOV      r4,r1
        MOV      r5,r0
        SUB      sp,sp,#0x24
        MOVS     r2,#0x16
        ADR      r1,|L1.340|
        ADD      r0,r0,#0x600
        BL       __aeabi_memcpy4
        MOV      r0,r5
        BL       GetHostIP
        CMP      r0,#0
        BNE      |L1.284|
        MOV      r0,r5
        BL       CreateConnection
        ADD      r6,r5,#0x62c
        STR      r0,[r5,#0x62c]
        CMP      r0,#0
        BGE      |L1.56|
        MOV      r0,#0xffffffff
|L1.52|
        ADD      sp,sp,#0x24
        POP      {r4-r7,pc}
|L1.56|
        ADD      r0,r5,#0x400
        LDR      r1,|L1.364|
        MOV      r7,r0
        BL       strcpy
        MOV      r0,r7
        BL       strlen
        MOV      r2,r0
        MOVS     r3,#0
        MOV      r1,r7
        LDR      r0,[r5,#0x62c]
        BL       sl_Send
        MOVS     r3,#0
        MOV      r2,#0x400
        MOV      r1,r5
        LDR      r0,[r6,#0]
        BL       sl_Recv
        MOV      r0,r5
        BL       strlen
        MOVS     r6,#0
        STRB     r6,[r5,r0]
        ADR      r1,|L1.368|
        MOV      r0,r5
        BL       strstr
        MOVS     r1,r0
        MOV      r0,r6
        BEQ      |L1.148|
        ADDS     r1,r1,#0xf
        B        |L1.140|
|L1.130|
        STRB     r2,[r4,r0]
        ADDS     r1,r1,#1
        ADDS     r0,r0,#1
        CMP      r0,#0x32
        BCS      |L1.148|
|L1.140|
        LDRB     r2,[r1,#0]
        CBZ      r2,|L1.148|
        CMP      r2,#0x22
        BNE      |L1.130|
|L1.148|
        STRB     r6,[r4,r0]
        ADR      r1,|L1.384|
        MOV      r0,r5
        BL       strstr
        MOVS     r1,r0
        MOV      r0,#0
        MOV      r3,sp
        BEQ      |L1.190|
        ADDS     r1,r1,#7
        B        |L1.182|
|L1.172|
        STRB     r2,[r3,r0]
        ADDS     r1,r1,#1
        ADDS     r0,r0,#1
        CMP      r0,#0x32
        BCS      |L1.190|
|L1.182|
        LDRB     r2,[r1,#0]
        CBZ      r2,|L1.190|
        CMP      r2,#0x2c
        BNE      |L1.172|
|L1.190|
        STRB     r6,[r3,r0]
        MOV      r0,r3
        BL       __hardfp_atof
        VMOV     r0,r1,d0
        BL       __aeabi_d2f
        VMOV     s0,r0
        BL       __hardfp_lrintf
        STR      r0,[r4,#0x14]
        ADR      r1,|L1.392|
        MOV      r0,r5
        BL       strstr
        MOVS     r1,r0
        MOV      r0,#0
        ADD      r3,sp,#0x10
        BEQ      |L1.256|
        ADDS     r1,r1,#0xc
        B        |L1.248|
|L1.238|
        STRB     r2,[r3,r0]
        ADDS     r1,r1,#1
        ADDS     r0,r0,#1
        CMP      r0,#0x32
        BCS      |L1.256|
|L1.248|
        LDRB     r2,[r1,#0]
        CBZ      r2,|L1.256|
        CMP      r2,#0x2c
        BNE      |L1.238|
|L1.256|
        STRB     r6,[r3,r0]
        MOV      r0,r3
        BL       __hardfp_atof
        VMOV     r0,r1,d0
        BL       __aeabi_d2iz
        STR      r0,[r4,#0x20]
        ADR      r1,|L1.404|
        MOV      r0,r5
        BL       strstr
        B        |L1.286|
|L1.284|
        B        |L1.334|
|L1.286|
        MOVS     r1,r0
        MOV      r0,#0
        BEQ      |L1.320|
        ADDS     r1,r1,#8
        B        |L1.312|
|L1.298|
        ADDS     r3,r4,r0
        ADDS     r1,r1,#1
        ADDS     r0,r0,#1
        STRB     r2,[r3,#0x47]
        CMP      r0,#0x32
        BCS      |L1.320|
|L1.312|
        LDRB     r2,[r1,#0]
        CBZ      r2,|L1.320|
        CMP      r2,#0x22
        BNE      |L1.298|
|L1.320|
        ADD      r0,r0,r4
        STRB     r6,[r0,#0x47]
        LDR      r0,[r5,#0x62c]
        BL       sl_Close
|L1.334|
        MOVS     r0,#0
        B        |L1.52|
        ENDP

        DCW      0x0000
|L1.340|
        DCB      "api.openweathermap.org",0
        DCB      0
|L1.364|
        DCD      ||.constdata||
|L1.368|
        DCB      """description""",0
        DCB      0
        DCB      0
|L1.384|
        DCB      """temp""",0
        DCB      0
|L1.392|
        DCB      """pressure""",0
        DCB      0
|L1.404|
        DCB      """name""",0
        DCB      0

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.constdata||, DATA, READONLY, ALIGN=2

        DCB      0x47,0x45,0x54,0x20
        DCB      0x2f,0x64,0x61,0x74
        DCB      0x61,0x2f,0x32,0x2e
        DCB      0x35,0x2f,0x77,0x65
        DCB      0x61,0x74,0x68,0x65
        DCB      0x72,0x3f,0x71,0x3d
        DCB      0x41,0x6e,0x74,0x69
        DCB      0x62,0x65,0x73,0x26
        DCB      0x75,0x6e,0x69,0x74
        DCB      0x73,0x3d,0x6d,0x65
        DCB      0x74,0x72,0x69,0x63
        DCB      0x26,0x41,0x50,0x50
        DCB      0x49,0x44,0x3d,0x33
        DCB      0x62,0x31,0x38,0x61
        DCB      0x63,0x39,0x33,0x66
        DCB      0x38,0x64,0x62,0x35
        DCB      0x38,0x66,0x38,0x33
        DCB      0x62,0x39,0x62,0x38
        DCB      0x32,0x30,0x36,0x38
        DCB      0x30,0x33,0x35,0x64
        DCB      0x32,0x32,0x64,0x20
        DCB      0x48,0x54,0x54,0x50
        DCB      0x2f,0x31,0x2e,0x31
        DCB      0x0d,0x0a,0x55,0x73
        DCB      0x65,0x72,0x2d,0x41
        DCB      0x67,0x65,0x6e,0x74
        DCB      0x3a,0x20,0x4b,0x65
        DCB      0x69,0x6c,0x0d,0x0a
        DCB      0x48,0x6f,0x73,0x74
        DCB      0x3a,0x61,0x70,0x69
        DCB      0x2e,0x6f,0x70,0x65
        DCB      0x6e,0x77,0x65,0x61
        DCB      0x74,0x68,0x65,0x72
        DCB      0x6d,0x61,0x70,0x2e
        DCB      0x6f,0x72,0x67,0x0d
        DCB      0x0a,0x41,0x63,0x63
        DCB      0x65,0x70,0x74,0x3a
        DCB      0x20,0x2a,0x2f,0x2a
        DCB      0x0d,0x0a,0x0d,0x0a
        DCB      0x00,0x00,0x00,0x00
        DCB      0x47,0x45,0x54,0x20
        DCB      0x68,0x74,0x74,0x70
        DCB      0x3a,0x2f,0x2f,0x61
        DCB      0x70,0x69,0x2e,0x74
        DCB      0x69,0x6d,0x65,0x7a
        DCB      0x6f,0x6e,0x65,0x64
        DCB      0x62,0x2e,0x63,0x6f
        DCB      0x6d,0x2f,0x3f,0x7a
        DCB      0x6f,0x6e,0x65,0x3d
        DCB      0x45,0x75,0x72,0x6f
        DCB      0x70,0x65,0x2f,0x50
        DCB      0x61,0x72,0x69,0x73
        DCB      0x26,0x66,0x6f,0x72
        DCB      0x6d,0x61,0x74,0x3d
        DCB      0x6a,0x73,0x6f,0x6e
        DCB      0x26,0x6b,0x65,0x79
        DCB      0x3d,0x47,0x5a,0x59
        DCB      0x44,0x55,0x38,0x57
        DCB      0x50,0x53,0x58,0x49
        DCB      0x32,0x20,0x48,0x54
        DCB      0x54,0x50,0x2f,0x31
        DCB      0x2e,0x31,0x0d,0x0a
        DCB      0x55,0x73,0x65,0x72
        DCB      0x2d,0x41,0x67,0x65
        DCB      0x6e,0x74,0x3a,0x20
        DCB      0x4b,0x65,0x69,0x6c
        DCB      0x0d,0x0a,0x48,0x6f
        DCB      0x73,0x74,0x3a,0x61
        DCB      0x70,0x69,0x2e,0x74
        DCB      0x69,0x6d,0x65,0x7a
        DCB      0x6f,0x6e,0x65,0x64
        DCB      0x62,0x2e,0x63,0x6f
        DCB      0x6d,0x0d,0x0a,0x41
        DCB      0x63,0x63,0x65,0x70
        DCB      0x74,0x3a,0x20,0x2a
        DCB      0x2f,0x2a,0x0d,0x0a
        DCB      0x0d,0x0a,0x00

        EXPORT getTime [CODE]
        EXPORT getWeather [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT __aeabi_memcpy4 [CODE]
        IMPORT GetHostIP [CODE]
        IMPORT CreateConnection [CODE]
        IMPORT strcpy [CODE]
        IMPORT strlen [CODE]
        IMPORT sl_Send [CODE]
        IMPORT sl_Recv [CODE]
        IMPORT strstr [CODE]
        IMPORT __hardfp_atof [CODE]
        IMPORT __aeabi_d2f [CODE]
        IMPORT __hardfp_lrintf [CODE]
        IMPORT __aeabi_d2iz [CODE]
        IMPORT sl_Close [CODE]
        IMPORT strcmp [CODE]
        IMPORT UARTprintf [CODE]
        IMPORT atoi [CODE]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
